# Site settings
title: Sot
email: sot234@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Trang web vui vẻ, không qoại.
baseurl: "/sot234" # the subpath of your site, e.g. /blog/
url: "http://sot234.github.io" # the base hostname & protocol for your site
twitter_username: sot234.github.io
github_username:  sot234.github.io

# Build settings
markdown: kramdown
