title: Sot
email: sot234@gmail.com
description: Trang web vui vẻ, không qoại.
baseurl: "/sot234" 
url: "http://sot234.github.io" 
twitter_username: sot234.github.io
github_username:  sot234.github.io

# Build settings
markdown: kramdown
